### ISSUE TITLE
AI and Utopia.90 and 91 in late game

### ISSUE THREAD

**Issue by MattMills** [Ariphaos/StellarisUnofficialPatch#13]
FYI, the AI can cause huge (10-15 minute) lag spikes by switching between utopia.90 and utopia.91 frequently, with thousands of pops.

Debugging a late game (~2470) vanilla game and debug_events shows 355113 events for utopia.90 and 642489 events for utopia.91. Player empire has 2100 pops, highest AI has ~4000 pops.

The game I'm debugging may have additional issues though as it also seems to be continuously retriggering on_planet_survey actions every daily tick.

**Comment by Ariphaos** [comment]
The AI doesn't use chemical bliss by default. Do you have some mod enacting it?

**Comment by MattMills** [comment]
So I was testing on someone else's save, but it is/was ironman. I was told UI overhaul dynamic and Tiny Outliner V2 so that's what I was testing with. I'll load it up and take a look and double check though.

**Comment by MattMills** [comment]
Looking at the vanilla code I think it's coming from here, I confirmed at least one of the AI is using chemical bliss:

scripted_effects/00_scripted_effects.txt
```
breach_fix_resolution_greatergood_universal_prosperity_mandate_chemical = {
	breach_fix_resolution_greatergood_universal_prosperity_mandate_freeslaves = yes

	if = {
		limit = {
			is_active_resolution = "resolution_greatergood_universal_prosperity_mandate"
			in_breach_of = resolution_greatergood_universal_prosperity_mandate
			has_technology = "tech_subdermal_stimulation"
		}
		hidden_effect = {
			every_owned_species = {
				limit = {
					is_sapient = yes
				}
				set_living_standard = { type = living_standard_chemical_bliss country = prev }
			}
		}

		custom_tooltip = "federations.10230.complychemical"
	}
}
```

Universal prosperity mandate is in effect in the GC.

**Comment by MattMills** [comment]
(And this AI is in breach)

**Comment by MattMills** [comment]
[llamaTic - ironman.sav.zip](https://github.com/Ariphaos/StellarisUnofficialPatch/files/8457214/llamaTic.-.ironman.sav.zip)

Original save if you want to look

**Comment by MattMills** [comment]
And I've confirmed that after I repeal Universal prosperty I see no more Utopia.91 events firing

**Comment by Ariphaos** [comment]
Alright I believe I have this fixed in the next patch.

Thank you.
