### ISSUE TITLE
'Erutite' trait modifier  vs 'intelligent' trait modifier?

### ISSUE THREAD

**Issue by The-Grim-Sleeper** [Ariphaos/StellarisUnofficialPatch#15]
The 'Erutite' and 'Enigmatic Intelligence' traits use an abberant modifier to change the research output 'planet_researchers_produces_mult'
Most species traits use the 'planet_jobs_<science type>_research_produces_mult modifier, including intelligent and the other Enigmatic Intelligence variants

I don't know if the difference has any impact in the way the trait works, or if it is just some legacy code with only a tooltip difference.
I can make a branch to implement the change, but I'd like to know for sure if it is even relevant.

**Comment by The-Grim-Sleeper** [comment]
So I posted on the Paradox forum and there might indeed be a functional difference. But whether or not is it sensible or intentional is something that is still under investigation.
https://forum.paradoxplaza.com/forum/threads/what-is-the-difference-between-the-erutite-modifier-and-the-modifier-research-other-traits-use.1538481/#post-28418324

**Comment by Ariphaos** [comment]
I was hemming and hawing over this for a bit, but decided to address this in my 3.5 patch. So, fixed.
