### ISSUE TITLE
[3.6.1] Invalid scope for mechanical empire attraction modifier for technologist faction.

### ISSUE THREAD

**Issue by SirBlackAxe** [Ariphaos/StellarisUnofficialPatch#17]
common\pop_faction_types\00_technologist.txt line 72 is trying to call `NOT = { has_trait = trait_mechanical }` from pop_faction scope, which is invalid. I believe `from` should be changed to `owner` so the trigger is being checked at country scope.

**Comment by Ariphaos** [comment]
Has been fixed, thank you.
