### ISSUE TITLE
puddle_technician_drone is worker

### ISSUE THREAD

**Issue by Toriansel** [Ariphaos/StellarisUnofficialPatch#19]
The puddle_technician_drone pop job is incorrectly defined as a worker (not a simple_drone) in the 03_worker_jobs.txt file instead of the 04_gestalt_jobs.txt file.

**Comment by Toriansel** [comment]
In patch 3.8 this job moved to 06_event_jobs.txt, but he drone version of the job is still setup as a worker job and not a drone job.

**Comment by Ariphaos** [comment]
Addressed in my 3.8 patch. Thank you.

**Comment by Toriansel** [comment]
Thanks for working this issue. There is still a minor issue with the puddle_technician_drone job definition. The possible_precalc line is setup as "can_fill_worker_job", but should be "can_fill_drone_job". Sorry I failed to notice this in the original bug report.
